const DATA_URL='https://raw.githubusercontent.com/itzsabik57/Course-Hub/main/course-hub-data.json';
let data={platforms:[]};let route={repo:null,node:null};
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1900)}
function showError(t){document.getElementById('loginError').textContent=t}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function login(){const id=document.getElementById('loginId').value.trim(),p=document.getElementById('loginPass').value;if(!id||!p)return showError('Enter your ID and password.');try{const x=window.__courseData||await loadData();const u=(x.accounts||[]).find(a=>a.id===id&&a.enabled!==false&&(a.password===p||a.passwordHash===await sha256(p)));if(!u)return showError('Invalid ID or password.');data=x.data||{platforms:[]};sessionStorage.setItem('course_hub_logged_in','1');document.getElementById('loginScreen').classList.add('public-hide');document.getElementById('site').classList.remove('public-hide');render();}catch(e){showError('Unable to load course data.')}}
async function loadData(){if(window.__courseData)return window.__courseData;const r=await fetch(DATA_URL+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw 0;window.__courseData=await r.json();return window.__courseData}
function logout(){sessionStorage.removeItem('course_hub_logged_in');location.reload()}
function uid(){return 'n_'+Date.now().toString(36)+Math.random().toString(36).slice(2,9)}
function node(type,name=''){return {id:uid(),type,name,image:'',youtube:'',children:[]}}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function typeLabel(t){return ({platform:'Platform',course:'Course',subject:'Subject / Class',chapter:'Chapter','chapter-part':'Chapter Part',lecture:'Lecture'}[t]||t)}
function icon(t){return ({platform:'▣',course:'▤',subject:'◈',chapter:'☰','chapter-part':'└',lecture:'▶'}[t]||'•')}
function find(root,id){if(root?.id===id)return root;for(const c of(root?.children||[])){const x=find(c,id);if(x)return x}return null}
function parentOf(root,id){if((root.children||[]).some(x=>x.id===id))return root;for(const c of(root.children||[])){const p=parentOf(c,id);if(p)return p}return null}
function goHome(){route={repo:null,node:null};render();closeModal()}
function goBack(){if(route.node){const r=repo(),p=parentOf(r,route.node);route.node=p&&p.id!==r.id?p.id:null;render()}else if(route.repo)goHome()}
function openRepo(id){route={repo:id,node:null};render()}
function openNode(id){const r=repo(),n=find(r,id);if(!n)return;if(n.type==='lecture'&&n.youtube){window.location.href=n.youtube;return}route.node=id;render()}
function render(){const a=document.getElementById('app');document.getElementById('backBtn').textContent=(route.repo||route.node)?'‹':'⌂';if(!route.repo)return renderHome(a);if(!route.node)return renderRepo(a,repo());return renderNode(a,repo(),find(repo(),route.node))}
function renderHome(a){a.innerHTML='<div class="page">'+(data.platforms.length?'<div class="grid">'+data.platforms.map(r=>`<button class="tile" onclick="openRepo('${r.id}')">${r.image?`<img class="tile-img" src="${r.image}" alt="">`:'<div class="tile-img" style="display:grid;place-items:center;font-size:30px;color:#747985">▣</div>'}<div class="tile-shade"></div><div class="tile-body"><div class="tile-title">${esc(r.name)}</div></div></button>`).join('')+'</div>':'<div class="empty">No platforms yet.</div>')+'</div>'}
function renderRepo(a,r){a.innerHTML=`<div class="page"><div class="page-head"><div><h1 class="title">${esc(r.name)}</h1></div></div>${r.children?.length?contentHTML(r.children):'<div class="empty">No content yet.</div>'}</div>`}
function renderNode(a,r,n){if(!n)return goHome();const kids=n.children||[];a.innerHTML=`<div class="page"><div class="hero">${n.image?`<img class="hero-img" src="${n.image}" alt="">`:''}<div><h1 class="hero-title">${esc(n.name)}</h1></div></div>${kids.length?contentHTML(kids):'<div class="empty">Nothing has been added here yet.</div>'}</div>`}
function contentHTML(list){if(!list.length)return '<div class="empty">Nothing has been added here yet.</div>';const t=list[0]?.type;if(t==='lecture')return listHTML(list);if(t==='chapter'||t==='chapter-part')return '<div class="box-grid">'+list.map(n=>`<button class="box-card" onclick="openNode('${n.id}')">${esc(n.name)}</button>`).join('')+'</div>';return '<div class="card-grid">'+list.map(n=>`<button class="content-card" onclick="openNode('${n.id}')">${n.image?`<img src="${n.image}" alt="">`:''}<div class="content-shade"></div><div class="content-name">${esc(n.name)}</div></button>`).join('')+'</div>'}
function listHTML(list){return '<div class="list">'+list.map(n=>`<button class="item-card" onclick="openNode('${n.id}')"><span class="item-icon">▶</span><span class="item-copy"><span class="item-name">${esc(n.name)}</span></span><span class="chev">›</span></button>`).join('')+'</div>'}
async function boot(){try{await loadData();if(sessionStorage.getItem('course_hub_logged_in')==='1'){const x=window.__courseData;data=x.data||{platforms:[]};document.getElementById('loginScreen').classList.add('public-hide');document.getElementById('site').classList.remove('public-hide');render()}}catch(e){showError('Unable to load course data from GitHub.')}}
boot();
